Fruits = ["APPLE", "BANANA", "ORANGE", "GRAPES", "POMEGRANATE", "WATERMELON", "PINEAPPLE", "MANGO", "STRAWBERRY", "BLUEBERRY",
          "PAPAYA", "KIWI", "GUAVA", "CHERRY", "APRICOT", "PEACH", "PLUM", "FIG", "CANTALOUPE", "HONEYDEW",
          "LYCHEE", "DRAGONFRUIT", "PASSIONFRUIT", "RASPBERRY", "BLACKBERRY", "CRANBERRY", "AVOCADO", "COCONUT", "LEMON",
          "LIME", "GRAPEFRUIT", "TANGERINE", "JACKFRUIT", "STARFRUIT", "PERSIMMON", "CLEMENTINE", "NECTARINE",
          "BLACKCURRANT", "GOOSEBERRY", "KUMQUAT", "RAMBUTAN", "MULBERRY", "DURIAN", "PAWPAW", "SOURSOP", "LOQUAT",
          "FEIJOA"]

Countries = ["USA", "CHINA", "INDIA", "TURKEY", "ITALY", "SPAIN", "BRAZIL", "MEXICO", "PAKISTAN", "IRAN",
             "INDONESIA", "PHILIPPINES", "VIETNAM", "THAILAND", "EGYPT", "SOUTH AFRICA", "GREECE", "PORTUGAL", "FRANCE", "ARGENTINA",
             "AUSTRALIA", "RUSSIA", "GERMANY", "CANADA", "NETHERLANDS", "SAUDI ARABIA", "UNITED KINGDOM", "COLOMBIA", "MALAYSIA",
             "NIGERIA", "BANGLADESH", "POLAND", "UKRAINE", "MOROCCO", "JAPAN", "PERU", "VENEZUELA", "KENYA", "CHILE", "IRAQ", "BELGIUM",
             "SWEDEN", "SWITZERLAND", "AUSTRIA", "NORWAY", "DENMARK", "FINLAND", "ROMANIA", "ISRAEL", "IRELAND", "SINGAPORE", "NEW ZEALAND",
             "HONG KONG", "HUNGARY", "CZECH REPUBLIC", "GHANA", "CAMEROON", "TANZANIA", "ALGERIA", "QATAR", "KAZAKHSTAN", "SUDAN",
             "SENEGAL", "UZBEKISTAN", "TUNISIA", "ANGOLA", "JORDAN", "CUBA", "SRI LANKA", "SERBIA", "BULGARIA", "ECUADOR", "NORWAY",
             "BAHRAIN", "PANAMA", "CROATIA", "LEBANON", "ETHIOPIA", "LITHUANIA", "GEORGIA", "SLOVAKIA", "URUGUAY", "SLOVENIA"]

Names = ["MOHAMMED", "FATIMA", "ALI", "AMINA", "AHMED", "AYA", "YOUSSEF", "LEILA", "IBRAHIM", "SARA",
         "OMAR", "NOUR", "KHALED", "LINA", "ABDULLAH", "MALAK", "HAMZA", "MAYA", "MUSTAFA", "NOOR",
         "YASIN", "NADA", "TAHA", "ZAHRA", "ZIAD", "HANA", "SAEED", "LEEN", "SAMIR", "MARIAM",
         "KARIM", "SALMA", "ANAS", "LAMA", "WALEED", "YASMINE", "TAHIR", "SANA", "SALEH", "AMAL",
         "ZAKARIA", "REEM", "KHALID", "INAS", "AYMAN", "RAWAN", "FAHAD", "NADIA", "MOUSA", "NADA",
         "AHMAD", "HABIBA", "BILAL", "RANA", "IBRAHIM", "AYSHA", "ALI", "NAWAL", "ISMAIL", "RAHMA",
         "ADNAN", "HAYAT", "TARIK", "FATIMA", "IMRAN", "REEM", "YUNUS", "HIBA", "RAFIQ", "RAZAN",
         "FAISAL", "SABIHA", "HAMID", "LAYLA", "TAHIR", "AMANI", "FAWAZ", "ZAINAB", "FAROUK", "HODA",
         "NASIR", "ASMA", "JAMAL", "RIM", "ANWAR", "NAHID", "MANSOUR", "SARAH", "IBRAHIM", "NAJWA"]

Sportsmen = ["STEVE JOBS", "MICHAEL JORDAN", "TOM BRADY", "KOBE BRYANT", "TIGER WOODS", "ROGER FEDERER", "CRISTIANO RONALDO",
             "LIONEL MESSI", "MICHAEL PHELPS", "USAIN BOLT", "CONOR MCGREGOR", "SERENA WILLIAMS", "LEWIS HAMILTON", "FLOYD MAYWEATHER JR.",
             "RAFAEL NADAL", "NOVAK DJOKOVIC", "VIRAT KOHLI", "LEBRON JAMES", "MANNY PACQUIAO", "KEVIN DURANT", "NEYMAR", "JAMES HARDEN",
             "STEPHEN CURRY", "KAWHI LEONARD", "DWYANE JOHNSON", "ANTHONY JOSHUA", "ZLATAN IBRAHIMOVIC", "KYLIAN MBAPPE", "ANTONIO BROWN",
             "RUSSELL WILSON", "LUKA DONCIC", "DREW BREES", "TRAVIS SCOTT", "JIMMY BUTLER", "KHABIB NURMAGOMEDOV", "GIANNIS ANTETOKOUNMPO",
             "LAMAR JACKSON", "EZEKIEL ELLIOTT", "CHRIS PAUL", "SAQUON BARKLEY", "JOEL EMBIID", "CARSON WENTZ", "PATRICK MAHOMES",
             "BEN SIMMONS", "BAKER MAYFIELD", "JAYSON TATUM", "CHRISTIAN MCCAFFREY", "KYLE KUZMA", "DAMIAN LILLARD", "DEVIN BOOKER",
             "DONOVAN MITCHELL", "JA MORANT", "ZION WILLIAMSON", "TRAE YOUNG", "BRANDON INGRAM", "D'ANGELO RUSSELL", "JAYLEN BROWN",
             "DE'AARON FOX", "COLLIN SEXTON", "COBY WHITE"]
Cars = ["TOYOTA", "HONDA", "FORD", "CHEVROLET", "BMW", "MERCEDES", "AUDI", "VOLKSWAGEN", "NISSAN", "HYUNDAI", "JEEP", "SUBARU", "LEXUS", "MAZDA", "KIA", "RENULT", "PEUGEOT", "GMC", "FIAT", "LAMBORGHINI"
        "FERRARI", "PAGANI", "KOENIGSEGG", "LUCID", "TESLA", "TOGG", "SKODA", "CHANGAN", "GEELY", "GAC", "OPEL", "HAVAL"
        "PORSCHE", "CADILLAC", "JEEP"]
